services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: erps
      POSTGRES_PASSWORD: erps
      POSTGRES_DB: erps
    ports:
      - '5432:5432'
    volumes:
      - erps_pg:/var/lib/postgresql/data

volumes:
  erps_pg:
